spring.application.name=oauth2

spring.security.oauth2.client.registration.google.client-id={get from google console}
spring.security.oauth2.client.registration.google.client-secret={get from google console}

spring.security.oauth2.client.registration.github.client-id={get from github developer settings}
spring.security.oauth2.client.registration.github.client-secret={get from github developer settings}
spring.security.oauth2.client.registration.github.scope=user:email, user:profile
spring.security.oauth2.client.registration.github.provider=github